# Generated by Django 4.1.1 on 2022-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeves', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='boysfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='girlsfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='menfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='womenfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boyscategory',
            name='boys',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='boysfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='girlscategory',
            name='girls',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='mencategory',
            name='men',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='womencategory',
            name='women',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
    ]
