# Generated by Django 4.1.1 on 2022-11-07 19:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sleeve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeves', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boysfashion',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='girlsfashion',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='menfashion',
            name='card_name',
        ),
        migrations.RemoveField(
            model_name='womenfashion',
            name='card_name',
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='discount',
            field=models.CharField(blank=True, choices=[('10%', '10% And Above'), ('20%', '20% And Above'), ('30%', '30% And Above'), ('40%', '40% And Above'), ('50%', '50% And Above'), ('60%', '60% And Above'), ('70%', '70% And Above')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='seller',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='boyscategory',
            name='boys',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='boysfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='girlscategory',
            name='girls',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='mencategory',
            name='men',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='womencategory',
            name='women',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packet_Contains', models.CharField(blank=True, max_length=100, null=True, verbose_name='Packet Contains')),
                ('Rise', models.CharField(blank=True, choices=[('Mid Rise', 'Mid Rise'), ('Low Rise', 'Low Rise'), ('High Rise', 'High Rise')], max_length=50, null=True, verbose_name='Rise')),
                ('Stretchable', models.BooleanField(blank=True, null=True, verbose_name='Stretchable')),
                ('Care_instructions', models.CharField(blank=True, max_length=200, null=True, verbose_name='Care Instructions')),
                ('Descriptions', models.TextField(null=True, verbose_name='Descriptions')),
                ('Color', models.ManyToManyField(to='ecomapp.color', verbose_name='Color')),
                ('Material', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.material', verbose_name='Material')),
                ('Neck', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.neck', verbose_name='Neck')),
                ('Occasion', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.occasion', verbose_name='Occasion')),
                ('Pattern', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pattern', verbose_name='Pattern')),
                ('Pocket', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pocket', verbose_name='Pocket')),
                ('Sleeves', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sleeve', verbose_name='Sleeves')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.CreateModel(
            name='WomenDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womenfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womencategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='MenDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.menfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.mencategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='GirlsDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlsfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlscategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='BoysDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boysfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boyscategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
    ]
