# Generated by Django 4.1.1 on 2022-09-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_alter_boyscategory_boys_alter_girlscategory_girls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boysfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='girlsfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='menfashion',
            old_name='card_name',
            new_name='seller',
        ),
        migrations.RenameField(
            model_name='womenfashion',
            old_name='card_name',
            new_name='seller',
        ),
    ]
