# Generated by Django 4.1.1 on 2022-10-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_color_kidsage_material_neck_occasion_pattern_pocket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packet_Contains', models.CharField(blank=True, max_length=100, null=True)),
                ('Rise', models.CharField(blank=True, choices=[], max_length=50, null=True)),
                ('Stretchable', models.BooleanField(blank=True, null=True)),
                ('Care_instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('Descriptions', models.TextField(null=True)),
                ('Color', models.ManyToManyField(to='ecomapp.color')),
                ('Material', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.material')),
                ('Neck', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.neck')),
                ('Occasion', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.occasion')),
                ('Pattern', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pattern')),
                ('Pocket', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pocket')),
                ('Sleeves', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sleeve')),
            ],
        ),
        migrations.CreateModel(
            name='WomenProduct',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womenfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womencategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='MenProduct',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.menfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.mencategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='GirlsProduct',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlsfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlscategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
        migrations.CreateModel(
            name='BoysProduct',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boysfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boyscategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
    ]
