# Generated by Django 4.1.1 on 2022-11-08 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecomapp', '0002_color_kidsage_material_neck_occasion_pattern_pocket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(blank=True)),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.size')),
            ],
        ),
    ]
