# Generated by Django 4.1.1 on 2022-10-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_productdetail_womenproduct_menproduct_girlsproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='Rise',
            field=models.CharField(blank=True, choices=[('Mid Rise', 'Mid Rise'), ('Low Rise', 'Low Rise'), ('High Rise', 'High Rise')], max_length=50, null=True),
        ),
    ]
