# Generated by Django 4.1.1 on 2022-10-13 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_rename_card_name_boysfashion_seller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='age',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.kidsage'),
        ),
    ]
