# Generated by Django 4.1.1 on 2022-11-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amnt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
