# Generated by Django 4.1.1 on 2022-10-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_kidsage_boysfashion_age_girlsfashion_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boysfashion',
            name='age',
        ),
        migrations.RemoveField(
            model_name='girlsfashion',
            name='age',
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='age',
            field=models.ManyToManyField(to='ecomapp.kidsage'),
        ),
    ]
