# Generated by Django 4.0.6 on 2022-10-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_alter_productdetail_rise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WomenProduct',
            new_name='BoysDetail',
        ),
        migrations.RenameModel(
            old_name='MenProduct',
            new_name='GirlsDetail',
        ),
        migrations.RenameModel(
            old_name='GirlsProduct',
            new_name='MenDetail',
        ),
        migrations.RenameModel(
            old_name='BoysProduct',
            new_name='WomenDetail',
        ),
        migrations.AlterField(
            model_name='boysdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boysfashion'),
        ),
        migrations.AlterField(
            model_name='boysdetail',
            name='Type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boyscategory'),
        ),
        migrations.AlterField(
            model_name='girlsdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlsfashion'),
        ),
        migrations.AlterField(
            model_name='girlsdetail',
            name='Type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.girlscategory'),
        ),
        migrations.AlterField(
            model_name='mendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.menfashion'),
        ),
        migrations.AlterField(
            model_name='mendetail',
            name='Type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.mencategory'),
        ),
        migrations.AlterField(
            model_name='womendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womenfashion'),
        ),
        migrations.AlterField(
            model_name='womendetail',
            name='Type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.womencategory'),
        ),
    ]
