# Generated by Django 4.1.1 on 2022-10-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_remove_boysfashion_age_remove_girlsfashion_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boyscategory',
            old_name='boys',
            new_name='kids',
        ),
        migrations.RenameField(
            model_name='girlscategory',
            old_name='girls',
            new_name='kids',
        ),
    ]
