# Generated by Django 4.1.1 on 2022-10-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_rename_womenproduct_boysdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='Material',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.material', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Neck',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.neck', verbose_name='Neck'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Occasion',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.occasion', verbose_name='Occasion'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Packet_Contains',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Packet Contains'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Pattern',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pattern', verbose_name='Pattern'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Pocket',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pocket', verbose_name='Pocket'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Rise',
            field=models.CharField(blank=True, choices=[('Mid Rise', 'Mid Rise'), ('Low Rise', 'Low Rise'), ('High Rise', 'High Rise')], max_length=50, null=True, verbose_name='Rise'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Sleeves',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sleeve', verbose_name='Sleeves'),
        ),
    ]
