# Generated by Django 4.1.1 on 2022-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_rename_boys_boyscategory_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysfashion',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
