# Generated by Django 4.1.1 on 2022-11-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_cartitem_quantity_alter_cartitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_qty',
            field=models.IntegerField(default=1),
        ),
    ]
