# Generated by Django 4.1.1 on 2022-10-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_productdetail_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='Care_instructions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Care Instructions'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Color',
            field=models.ManyToManyField(to='ecomapp.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Descriptions',
            field=models.TextField(null=True, verbose_name='Descriptions'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Stretchable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Stretchable'),
        ),
    ]
