# Generated by Django 4.1.1 on 2022-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_alter_boysfashion_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='size',
            field=models.ManyToManyField(to='ecomapp.size'),
        ),
    ]
