# Generated by Django 4.1.1 on 2022-11-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_cart_total_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_qty',
            field=models.IntegerField(default=0),
        ),
    ]
