# Generated by Django 4.1.1 on 2022-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_cart_total_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
