# Generated by Django 4.1.1 on 2022-10-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_size_boysfashion_size_girlsfashion_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='description',
            field=models.CharField(max_length=60),
        ),
    ]
