# Generated by Django 4.1.1 on 2022-11-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_cartitem_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
