# Generated by Django 4.1.1 on 2022-11-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0010_cartitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysfashion',
            name='dlvry_charges',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='boysfashion',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='dlvry_charges',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='girlsfashion',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='dlvry_charges',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='menfashion',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='dlvry_charges',
            field=models.CharField(default='FREE', max_length=100),
        ),
        migrations.AddField(
            model_name='womenfashion',
            name='mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boysfashion',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
