# Generated by Django 4.1.1 on 2022-11-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_seller_productdetail_manufacture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
