# Generated by Django 4.1.1 on 2022-11-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0015_productdetail_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='country',
            new_name='Country',
        ),
    ]
