# Generated by Django 4.1.1 on 2022-11-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0016_rename_country_productdetail_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='about_us',
            field=models.TextField(unique=True),
        ),
    ]
