# Generated by Django 4.1.1 on 2022-11-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0017_alter_seller_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='Country',
            new_name='Country_of_origin',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.AddField(
            model_name='brand',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='about_us',
            field=models.TextField(null=True),
        ),
    ]
