# Generated by Django 4.1.1 on 2022-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0018_rename_country_productdetail_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='join_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
