# Generated by Django 4.1.1 on 2022-11-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_seller_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
    ]
