# Generated by Django 4.1.1 on 2022-11-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_alter_brand_about_alter_seller_about_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boysfashion',
            old_name='description',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='girlsfashion',
            old_name='description',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='menfashion',
            old_name='description',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='womenfashion',
            old_name='description',
            new_name='title',
        ),
    ]
