# Generated by Django 4.1.1 on 2022-11-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_rename_description_boysfashion_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='Manufacture_address',
        ),
        migrations.RemoveField(
            model_name='productdetail',
            name='Return_policy',
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Manufacture',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
