# Generated by Django 4.1.1 on 2022-11-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0022_remove_productdetail_manufacture_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='Country_of_origin',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='Return_exchange',
            new_name='Return',
        ),
    ]
