# Generated by Django 4.1.1 on 2022-11-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_rename_country_of_origin_productdetail_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='Country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Return',
            field=models.IntegerField(default=7),
        ),
    ]
