# Generated by Django 4.1.1 on 2022-11-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0024_alter_productdetail_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boysfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='girlsfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='menfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='womenfashion',
            name='brand',
        ),
    ]
