# Generated by Django 4.1.1 on 2022-11-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0026_boysfashion_brand_girlsfashion_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_dscnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total_mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.brand'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
