# Generated by Django 4.1.1 on 2022-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0027_cart_total_dscnt_cartitem_total_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='dlvry_chrg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery',
            field=models.IntegerField(default=0),
        ),
    ]
