# Generated by Django 4.1.1 on 2022-11-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0028_cart_dlvry_chrg_cartitem_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dlvry_chrg',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='delivery',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
