# Generated by Django 4.1.1 on 2022-11-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0029_alter_cart_dlvry_chrg_alter_cartitem_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dlvry_chrg',
            field=models.CharField(default='FREE', max_length=30),
        ),
    ]
