# Generated by Django 4.1.1 on 2022-11-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ecomapp', '0031_cartitem_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveItForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=60, null=True)),
                ('total_price', models.IntegerField()),
                ('total_mrp', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.brand')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.seller')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.size')),
            ],
        ),
    ]
