# Generated by Django 4.1.1 on 2022-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0032_saveitforlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveitforlater',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
