# Generated by Django 4.1.1 on 2022-11-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0033_saveitforlater_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveitforlater',
            name='cart',
        ),
    ]
