# Generated by Django 4.1.1 on 2022-11-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0035_saveitforlater_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saveitforlater',
            old_name='cart_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='saveitforlater',
            old_name='total_mrp',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='saveitforlater',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='saveitforlater',
            old_name='quantity',
            new_name='qty',
        ),
    ]
