# Generated by Django 4.1.1 on 2022-11-23 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0036_rename_cart_image_saveitforlater_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysfashion',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boys_brands', to='ecomapp.brand'),
        ),
        migrations.AlterField(
            model_name='girlsfashion',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='girls_brands', to='ecomapp.brand'),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='men_brands', to='ecomapp.brand'),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='women_brands', to='ecomapp.brand'),
        ),
    ]
