# Generated by Django 4.1.1 on 2022-11-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0037_alter_boysfashion_brand_alter_girlsfashion_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boys_products', to='ecomapp.boysfashion'),
        ),
        migrations.AlterField(
            model_name='girlsdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='girls_products', to='ecomapp.girlsfashion'),
        ),
        migrations.AlterField(
            model_name='mendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='men_products', to='ecomapp.menfashion'),
        ),
        migrations.AlterField(
            model_name='womendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='women_products', to='ecomapp.womenfashion'),
        ),
    ]
