# Generated by Django 4.1.1 on 2022-11-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0038_alter_boysdetail_product_alter_girlsdetail_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boyscategory',
            old_name='boys',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='girlscategory',
            old_name='girls',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mencategory',
            old_name='men',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='womencategory',
            old_name='women',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='boysdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.boysfashion'),
        ),
        migrations.AlterField(
            model_name='girlsdetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.girlsfashion'),
        ),
        migrations.AlterField(
            model_name='mendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.menfashion'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Rise',
            field=models.CharField(blank=True, choices=[('Mid Waist', 'Mid Waist'), ('Low Waist', 'Low Waist'), ('High Waist', 'High Waist')], max_length=50, null=True, verbose_name='Rise'),
        ),
        migrations.AlterField(
            model_name='womendetail',
            name='Product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.womenfashion'),
        ),
    ]
