# Generated by Django 4.1.1 on 2022-11-28 05:58

from django.db import migrations, models
import django.db.models.deletion
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0039_rename_boys_boyscategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsFashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_image', models.ImageField(upload_to=ecomapp.models.user_directory_path)),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField(default=0)),
                ('dlvry_charges', models.CharField(default='FREE', max_length=100)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Girls', 'Girls'), ('Boys', 'Boys')], max_length=50)),
                ('age', models.ManyToManyField(to='ecomapp.kidsage')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids_brands', to='ecomapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.boyscategory')),
                ('size', models.ManyToManyField(to='ecomapp.size')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KidsDetail',
            fields=[
                ('productdetail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ecomapp.productdetail')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.kidsfashion')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.kidscategory')),
            ],
            bases=('ecomapp.productdetail',),
        ),
    ]
