# Generated by Django 4.1.1 on 2022-12-01 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0042_remove_boysdetail_product_remove_boysdetail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.size'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Packet_Contains',
            field=models.CharField(max_length=100, null=True, verbose_name='Packet Contains'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='Sleeves',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sleeve', verbose_name='sleeves'),
        ),
    ]
