# Generated by Django 4.1.3 on 2022-12-04 08:53

from django.db import migrations, models
import django.db.models.deletion
import ecomapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0043_alter_cartitem_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('girls', 'girls'), ('boys', 'boys'), ('women', 'women'), ('men', 'men')], max_length=50)),
                ('card_image', models.ImageField(upload_to=ecomapp.models.user_directory_path)),
                ('title', models.CharField(max_length=60, unique=True)),
                ('price', models.IntegerField()),
                ('mrp', models.IntegerField(default=0)),
                ('dlvry_charges', models.CharField(default='FREE', max_length=100)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('discount', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.ManyToManyField(blank=True, to='ecomapp.kidsage')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_brands', to='ecomapp.brand')),
                ('size', models.ManyToManyField(blank=True, to='ecomapp.size')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductDetail',
            new_name='AllDetail',
        ),
        migrations.RemoveField(
            model_name='kidsdetail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='kidsdetail',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='kidsdetail',
            name='productdetail_ptr',
        ),
        migrations.RemoveField(
            model_name='kidsfashion',
            name='age',
        ),
        migrations.RemoveField(
            model_name='kidsfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='kidsfashion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kidsfashion',
            name='size',
        ),
        migrations.RemoveField(
            model_name='mendetail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='mendetail',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='mendetail',
            name='productdetail_ptr',
        ),
        migrations.RemoveField(
            model_name='menfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='menfashion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menfashion',
            name='size',
        ),
        migrations.RemoveField(
            model_name='saveitforlater',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='saveitforlater',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='saveitforlater',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='saveitforlater',
            name='size',
        ),
        migrations.RemoveField(
            model_name='saveitforlater',
            name='user',
        ),
        migrations.RemoveField(
            model_name='womendetail',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='womendetail',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='womendetail',
            name='productdetail_ptr',
        ),
        migrations.RemoveField(
            model_name='womenfashion',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='womenfashion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='womenfashion',
            name='size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='object_id',
        ),
        migrations.DeleteModel(
            name='KidsCategory',
        ),
        migrations.DeleteModel(
            name='KidsDetail',
        ),
        migrations.DeleteModel(
            name='KidsFashion',
        ),
        migrations.DeleteModel(
            name='MenCategory',
        ),
        migrations.DeleteModel(
            name='MenDetail',
        ),
        migrations.DeleteModel(
            name='MenFashion',
        ),
        migrations.DeleteModel(
            name='SaveItForLater',
        ),
        migrations.DeleteModel(
            name='WomenCategory',
        ),
        migrations.DeleteModel(
            name='WomenDetail',
        ),
        migrations.DeleteModel(
            name='WomenFashion',
        ),
    ]
