# Generated by Django 4.1.1 on 2022-12-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0043_alter_cartitem_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidsfashion',
            name='size',
            field=models.ManyToManyField(blank=True, to='ecomapp.size'),
        ),
        migrations.AlterField(
            model_name='menfashion',
            name='size',
            field=models.ManyToManyField(blank=True, to='ecomapp.size'),
        ),
        migrations.AlterField(
            model_name='womenfashion',
            name='size',
            field=models.ManyToManyField(blank=True, to='ecomapp.size'),
        ),
    ]
