# Generated by Django 4.1.1 on 2022-12-02 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0044_alter_kidsfashion_size_alter_menfashion_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveitforlater',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.size'),
        ),
    ]
