# Generated by Django 4.1.3 on 2022-12-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0046_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfashion',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.category'),
            preserve_default=False,
        ),
    ]
