# Generated by Django 4.1.3 on 2022-12-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0048_alldetail_delete_saveitforlater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllDetail',
        ),
    ]
