# Generated by Django 4.1.3 on 2022-12-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0049_delete_alldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Packet_Contains', models.CharField(max_length=100, null=True, verbose_name='Packet Contains')),
                ('Rise', models.CharField(blank=True, choices=[('Mid Waist', 'Mid Waist'), ('Low Waist', 'Low Waist'), ('High Waist', 'High Waist')], max_length=50, null=True, verbose_name='Rise')),
                ('Stretchable', models.BooleanField(blank=True, null=True, verbose_name='Stretchable')),
                ('Care_instructions', models.CharField(blank=True, max_length=200, null=True, verbose_name='Care Instructions')),
                ('Descriptions', models.TextField(null=True, verbose_name='Descriptions')),
                ('Country', models.CharField(default='India', max_length=50)),
                ('Manufacture', models.CharField(max_length=1000, null=True)),
                ('Return', models.IntegerField(default=7)),
                ('Color', models.ManyToManyField(to='ecomapp.color', verbose_name='Color')),
                ('Material', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.material', verbose_name='Material')),
                ('Neck', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.neck', verbose_name='Neck')),
                ('Occasion', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.occasion', verbose_name='Occasion')),
                ('Pattern', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pattern', verbose_name='Pattern')),
                ('Pocket', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.pocket', verbose_name='Pocket')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecomapp.allfashion')),
                ('Sellers', models.ManyToManyField(to='ecomapp.seller')),
                ('Sleeves', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.sleeve', verbose_name='sleeves')),
                ('Type', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.category')),
            ],
        ),
    ]
