# Generated by Django 4.1.3 on 2022-12-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0053_remove_cartitem_cart_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
