# Generated by Django 4.1.3 on 2022-12-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0055_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
