# Generated by Django 4.1.3 on 2022-12-04 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0058_saveforlater_delete_saveitforlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomcartitem',
            name='cartitems',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='caritems', to='ecomapp.allfashion'),
            preserve_default=False,
        ),
    ]
