# Generated by Django 4.1.3 on 2022-12-04 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0059_ecomcartitem_cartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomcartitem',
            name='cartitems',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='ecomapp.allfashion'),
        ),
    ]
