# Generated by Django 4.1.3 on 2022-12-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0060_alter_ecomcartitem_cartitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomcartitem',
            old_name='cartitems',
            new_name='products',
        ),
    ]
