# Generated by Django 4.1.3 on 2022-12-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0061_rename_cartitems_ecomcartitem_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfashion',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
