# Generated by Django 4.1.3 on 2022-12-11 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0063_alter_allfashion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Type',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='ecomapp.category'),
        ),
    ]
