# Generated by Django 4.1.3 on 2022-12-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0065_alter_productinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfashion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='ecomapp.category'),
        ),
    ]
