# Generated by Django 4.1.3 on 2023-01-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_alter_size_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_product',
            name='specificaions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to='ecommapp.size'),
            preserve_default=False,
        ),
    ]
