# Generated by Django 4.1.3 on 2023-01-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0003_seller_product_specificaions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_product',
            name='specificaions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specifics', to='ecommapp.size'),
        ),
    ]
