# Generated by Django 4.1.3 on 2023-01-06 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0004_alter_seller_product_specificaions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_product',
            old_name='specificaions',
            new_name='specifications',
        ),
    ]
