# Generated by Django 4.1.3 on 2023-01-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0005_rename_specificaions_seller_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcomCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amnt', models.IntegerField(default=0)),
                ('total_dscnt', models.IntegerField(default=0)),
                ('total_qty', models.IntegerField(default=0)),
                ('dlvry_chrg', models.CharField(default='FREE', max_length=30)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcomCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=60, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('delivery', models.CharField(default=0, max_length=30)),
                ('total_price', models.IntegerField()),
                ('total_mrp', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.brand')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.ecomcart')),
                ('carted_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='ecommapp.allfashion')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.seller_product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.size')),
            ],
        ),
    ]
