# Generated by Django 4.1.3 on 2023-01-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0007_alter_size_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomcartitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_cart', to='ecommapp.size'),
        ),
    ]
