# Generated by Django 4.1.3 on 2023-01-09 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0008_alter_ecomcartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecomcartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_ecom', to='ecommapp.ecomcart'),
        ),
    ]
