# Generated by Django 4.1.3 on 2023-01-10 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0009_alter_ecomcartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveForLater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=60, null=True)),
                ('qty', models.IntegerField(default=1)),
                ('all_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.allfashion')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.brand')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.seller_product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommapp.size')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
