# Generated by Django 4.1.3 on 2023-01-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0010_saveforlater'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='discnt_cat',
            field=models.CharField(default='Below 10%', max_length=100),
        ),
    ]
