# Generated by Django 4.1.3 on 2023-01-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0013_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='Type',
        ),
    ]
