# Generated by Django 4.1.3 on 2023-01-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0016_productinfo_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfashion',
            name='age',
            field=models.ManyToManyField(to='ecommapp.kidsage'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Care_instructions',
            field=models.CharField(max_length=200, null=True, verbose_name='Care Instructions'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Neck',
            field=models.CharField(max_length=255, null=True, verbose_name='Neck'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Pocket',
            field=models.CharField(max_length=255, null=True, verbose_name='Pocket'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Rise',
            field=models.CharField(choices=[('Mid Waist', 'Mid Waist'), ('Low Waist', 'Low Waist'), ('High Waist', 'High Waist')], max_length=50, null=True, verbose_name='Rise'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Sleeves',
            field=models.CharField(max_length=255, null=True, verbose_name='Sleeves'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Stretchable',
            field=models.BooleanField(null=True, verbose_name='Stretchable'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='about_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
