# Generated by Django 4.1.3 on 2023-01-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0017_alter_allfashion_age_alter_brand_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfashion',
            name='Products',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pros', to='ecommapp.productinfo'),
        ),
    ]
