# Generated by Django 4.1.3 on 2023-01-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0019_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfashion',
            name='age',
            field=models.ManyToManyField(null=True, to='ecommapp.kidsage'),
        ),
    ]
