# Generated by Django 4.1.3 on 2023-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0020_alter_allfashion_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfashion',
            name='age',
            field=models.ManyToManyField(blank=True, to='ecommapp.kidsage'),
        ),
    ]
