# Generated by Django 4.1.3 on 2023-01-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0021_alter_allfashion_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='Neck',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Neck'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Pocket',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pocket'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Rise',
            field=models.CharField(blank=True, choices=[('Mid Waist', 'Mid Waist'), ('Low Waist', 'Low Waist'), ('High Waist', 'High Waist')], max_length=50, null=True, verbose_name='Rise'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Sleeves',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sleeves'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='Stretchable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Stretchable'),
        ),
    ]
