# Generated by Django 4.1.3 on 2023-01-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0022_alter_productinfo_neck_alter_productinfo_pocket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='discnt_cat',
            field=models.CharField(blank=True, default='Below 10%', max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
